### ISSUE TITLE
No content for some valid verses

### ISSUE THREAD

**Issue by dalevross** [Glowstudent777/YouVersion-API#1]
When I attempt to request some valid verses I get blank content.
Here are a few of the verses that have this issue
Numbers 34: 13
Numbers 34: 14
Numbers 34: 15
Numbers 34: 16
Numbers 34: 17
Numbers 34: 18
Numbers 34: 19
Numbers 34: 21
Numbers 35: 14:

**Comment by Glowstudent777** [comment]
After reviewing the code and some debugging, I've determined it is an issue on YouVersions side. I'll open a ticket with them and get it resolved. Here is an explanation of the problem:

We parse the separate pages like this:
```
https://www.bible.com/bible/1/NUM.34.12
```

The verses you are trying to request from YouVersion like the following, redirect to `JHN.1.KJV`.
```
https://www.bible.com/bible/1/NUM.34.13
```

When a page is not what we are expecting we cannot parse the correct text and that results in either no content or an error.

**Comment by dalevross** [comment]
Thanks for taking a look at it so quickly!

**Comment by Glowstudent777** [comment]
No problem, waiting for a reply back from YouVersion. I'll make another comment if/when they respond.

**Comment by Glowstudent777** [comment]
Hi, I received an email back from YouVersion. The issue has been sent to their engineering team and is being investigated.

> Thank you for being a part of the YouVersion Community and taking time to reach out about the issue you are experiencing. We apologize for any inconvenience or frustration this may be causing. At this time, the known issue has been reported to our Engineering team and is being investigated. When the YouVersion Community pitches in to share information about problems with our systems, it helps us isolate and correct them quickly. We greatly appreciate your patience and understanding.

**Comment by dalevross** [comment]
Thanks, I'll give it a run. Just an FYI, I like pi, a lot. So I ran into this issue trying to find all bible verses that have the digits 3, 1 and 4 in it. I just find it a little cool that you notified me of the fix on a date that contains those digits :). Even has 3, 1, 4 and 2 which is an extension of the same search I did.

**Comment by dalevross** [comment]
Hi again,

I verified that all the verses that I had an interest in are working as I expected. I think you can safely close this issue.

**Comment by Glowstudent777** [comment]
Thanks for verifying. Happy coding!
